# Generated by Django 4.1.3 on 2024-03-11 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('date_birth', models.DateField(verbose_name='Дата рождения')),
                ('passport_series', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес проживания')),
                ('files', models.FileField(upload_to='', verbose_name='Файл')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documents')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
