# Generated by Django 4.1.3 on 2024-03-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_status_applications_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.status'),
        ),
    ]
